### ISSUE TITLE
Email registration failed

### ISSUE THREAD

**Issue by Ultr4fly** [pellaeon/registration#199]
### Steps to reproduce
1. register new user with Email registration app

### Expected behaviour
send email notification

### Actual behaviour
Internal Server error 

### Server configuration
**Operating system**: Ubuntu 18.04 LTS

**Web server:** Server version: Apache/2.4.29 (Ubuntu)

**Database:** mysqld  Ver 5.7.29-0ubuntu0.18.04.1 for Linux on x86_64 ((Ubuntu))

**PHP version:** PHP 7.2.28-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:23:25) (                                                            NTS )

**Nextcloud version:** (see Nextcloud admin page) Nextcloud 16.0.9

App  Registration 0.4.7

Applist:
<details>
```
sudo -u www-data php occ app:list

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - apporder: 0.9.0
  - audioplayer: 2.9.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.5.0
  - calendar: 1.7.2
  - camerarawpreviews: 0.7.3
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.2.0
  - dav: 1.9.2
  - deck: 0.6.6
  - drawio: 0.9.5
  - drop_account: 0.1.0
  - dropit: 0.4.0
  - event_update_notification: 0.3.4
  - extract: 1.2.3
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_fulltextsearch: 1.3.6
  - files_fulltextsearch_tesseract: 1.3.2
  - files_mindmap: 0.0.20
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - fulltextsearch: 1.3.8
  - fulltextsearch_elasticsearch: 1.3.6
  - gallery: 18.3.0
  - gpxedit: 0.0.13
  - gpxmotion: 0.0.11
  - gpxpod: 4.1.1
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.17.0
  - metadata: 0.11.1
  - music: 0.13.0
  - nextcloud_announcements: 1.5.0
  - notes: 3.2.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - phonetrack: 0.5.2
  - polls: 1.3.0
  - preferred_providers: 1.4.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - registration: 0.4.7
  - serverinfo: 1.6.0
  - socialsharing_email: 1.0.6
  - spreed: 6.0.4
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.12.1
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - unsplash: 1.1.5
  - updatenotification: 1.6.0
  - viewer: 1.2.0
  - workflowengine: 1.6.0
Disabled:
  - announcementcenter
  - dashboard
  - encryption
  - files_downloadactivity
  - groupfolders
  - quota_warning
  - richdocuments
  - sharebymail
  - user_ldap
  - workflow_pdf_converter
</details>



Note: i changed the email in the log below but kept the format. The problem exists only with this one email address: a.bcde@gmx.de. I tried a lot of other mail provider including gmail, web.de and had no problems. I suspected that the . in the mail address is causing problems but it works with another email with a .
When i changed the problem email from a.bcde@gmx**.de** to a.bcde@gmx**.net** it is working: teh mail is send. Of course gmx answers with "mailbox unavailable". 

<summary>Nextcloud Internal Server Error:</summary>
<details>

Interner Serverfehler
Der Server konnte die Anfrage nicht fertig stellen.

Sollte dies erneut auftreten, senden Sie bitte die nachfolgenden technischen Einzelheiten an Ihren Server-Administrator.

Weitere Details können im Server-Protokoll gefunden werden.

Technische Details
Entfernte Adresse: 192.168.0.45
Anfragekennung: sfY48KlfBVm7NHXAAkEU
Typ: OCP\AppFramework\Db\MultipleObjectsReturnedException
Code: 0
Nachricht: Did not expect more than one result when executing: query "SELECT * FROM `*PREFIX*registration` WHERE `email` = ? "; parameters Array ( [0] => a.bcde@gmx.de ) ; limit ""; offset ""
Datei: /var/www/html/nextcloud/lib/public/AppFramework/Db/Mapper.php
Zeile: 293

Trace
#0 /var/www/html/nextcloud/lib/public/AppFramework/Db/Mapper.php(372): OCP\AppFramework\Db\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)
#1 /var/www/html/nextcloud/apps/registration/db/registrationmapper.php(72): OCP\AppFramework\Db\Mapper->findEntity('SELECT * FROM `...', Array)
#2 /var/www/html/nextcloud/apps/registration/service/registrationservice.php(159): OCA\Registration\Db\RegistrationMapper->find('a.bcde@gmx.de')
#3 /var/www/html/nextcloud/apps/registration/controller/registercontroller.php(84): OCA\Registration\Service\RegistrationService->validateEmail('a.bcde@gmx.de')
#4 /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(166): OCA\Registration\Controller\RegisterController->validateEmail('a.bcde@gmx.de')
#5 /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(99): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Registration\Controller\RegisterController), 'validateEmail')
#6 /var/www/html/nextcloud/lib/private/AppFramework/App.php(126): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Registration\Controller\RegisterController), 'validateEmail')
#7 /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\Registratio...', 'validateEmail', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#8 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#9 /var/www/html/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#10 /var/www/html/nextcloud/lib/base.php(972): OC\Route\Router->match('/apps/registrat...')
#11 /var/www/html/nextcloud/index.php(42): OC::handleRequest()
#12 {main}

</details>

<summary>Nextcloud server log;</summary>
Here you can see that one email is working and the other not:
<details>
`
Error	index	OCP\AppFramework\Db\MultipleObjectsReturnedException: Did not expect more than one result when executing: query "SELECT * FROM `*PREFIX*registration` WHERE `email` = ? "; parameters Array ( [0] => a.bcde@gmx.de ) ; limit ""; offset ""	
2020-03-19T11:51:44+0100


Debug	core	Sent mail to "Array ( [a.bcde@gmx.net] => ) " with subject "Bestätigen Sie Ihre Nextcloud Registrierungsanfrage"
`
</details>

I can provide more details or logs if needed. Thank you in advance.

**Comment by pellaeon** [comment]
The error says you have more then one pending registration of email "a.bcde@gmx.de" in the database. But the code has checks in place to not put in duplicate items. Can you check your database to see if there is existing rows with that email?

You can just run `SELECT * FROM *PREFIX*registration WHERE email="a.bcde@gmx.de"` and see how many results are returned.

**Comment by himpierre** [comment]
@pellaeon Thanks, had the same error. There were indeed duplicate entries. Deleting them solved my issue.

cheers, t.
