### ISSUE TITLE
Bug on registration

### ISSUE THREAD

**Issue by pierreozoux** [pellaeon/registration#20]
From time to time (not always) I get a nasty:

```

Internal Server Error

The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.

More details can be found in the server log.

Technical details

    Remote Address: 82.234.61.89
    Request ID: YkEbzKjbJhKeYE/i1/QP
```

Here is the log from the server:
```
{"reqId":"YkEbzKjbJhKeYE\/i1\/QP","remoteAddr":"82.234.61.89","app":"index","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\InvalidParameterException\",\"Message\":\"Parameter \\\"token\\\" for route \\\"registration.register.verifyToken\\\" must match \\\"[^\\\/]++\\\" (\\\"cjBSo5EENpCrMrsfIdIz5e3LUa\\\/YIq\\\" given) to generate a corresponding URL.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php(140): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'registration.re...', false, Array, Array)\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/route\\\/router.php(306): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('registration.re...', Array, false)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/route\\\/cachingrouter.php(53): OC\\\\Route\\\\Router->generate('registration.re...', Array, false)\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/urlgenerator.php(65): OC\\\\Route\\\\CachingRouter->generate('registration.re...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/apps\\\/registration\\\/controller\\\/registercontroller.php(101): OC\\\\URLGenerator->linkToRoute('registration.re...', Array)\\n#5 [internal function]: OCA\\\\Registration\\\\Controller\\\\RegisterController->validateEmail()\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Registration\\\\Controller\\\\RegisterController), 'validateEmail')\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Registration\\\\Controller\\\\RegisterController), 'validateEmail')\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('RegisterControl...', 'validateEmail', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(867): OC\\\\Route\\\\Router->match('\\\/apps\\\/registrat...')\\n#13 \\\/var\\\/www\\\/html\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":167}","level":4,"time":"2015-08-15T14:43:55+00:00"}
```

Do you have an idea of where it could come from?
Please let me know if you need any more details to investigate.

You can try to reproduce on this installation:
https://framadrive.org/

Thanks a lot!

**Comment by pellaeon** [comment]
This have been fixed in 29379c373dc00e5319c1f975de3a2053e5a60002

**Comment by pierreozoux** [comment]
Looks like it is working now! Thanks a lot :)

**Comment by pierreozoux** [comment]
And thanks to you, we are almost ready!

https://framadrive.org/

(framasoft is a french association with mission to degooglise Internet :) http://degooglisons-internet.org/ )
Thanks to your great work, we are one step closer ;)
