### ISSUE TITLE
Got internal Server Error after send up registration and login.

### ISSUE THREAD

**Issue by xXSTrikeXx** [pellaeon/registration#57]
nextcloud.log
`{"reqId":"x","remoteAddr":"","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(136): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(199): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL, false)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":543}","level":3,"time":"2017-01-26T16:41:28+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","user":"Test4","version":"11.0.1.2"}
{"reqId":"x","remoteAddr":"":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(136): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(199): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL, false)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":543}","level":3,"time":"2017-01-26T16:41:29+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","user":"Test4","version":"11.0.1.2"}
{"reqId":"x","remoteAddr":"","app":"index","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"$absolutePath must be relative to \\\"files\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1900): OC\\\\Files\\\\View->getPathRelativeToFiles('\\\/Test4')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1997): OC\\\\Files\\\\View->lockPath('\\\/Test4', 1, false)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1295): OC\\\\Files\\\\View->lockFile('\\\/Test4', 1)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1342): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\FilesAccessControl\\\\StorageWrapper), '', '\\\/Test4')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(196): OC\\\\Files\\\\View->getFileInfo('\\\/Test4')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(131): OC\\\\Files\\\\Node\\\\Root->get('\\\/Test4')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(377): OC\\\\Files\\\\Node\\\\Folder->nodeExists('\\\/Test4')\\n#7 [internal function]: OC\\\\Files\\\\Node\\\\Root->getUserFolder('Test4')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(65): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(282): OC\\\\Files\\\\Node\\\\LazyRoot->__call('getUserFolder', Array)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Server.php(947): OC\\\\Files\\\\Node\\\\LazyRoot->getUserFolder('Test4')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/gallery\\\/appinfo\\\/application.php(236): OC\\\\Server->getUserFolder('Test4')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Gallery\\\\AppInfo\\\\Application->OCA\\\\Gallery\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(115): Pimple\\\\Container->offsetGet('UserFolder')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('UserFolder')\\n#15 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/gallery\\\/appinfo\\\/application.php(262): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('UserFolder')\\n#16 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Gallery\\\\AppInfo\\\\Application->OCA\\\\Gallery\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#17 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(115): Pimple\\\\Container->offsetGet('Environment')\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('Environment')\\n#19 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/gallery\\\/appinfo\\\/application.php(329): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('Environment')\\n#20 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Gallery\\\\AppInfo\\\\Application->OCA\\\\Gallery\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#21 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(115): Pimple\\\\Container->offsetGet('ConfigService')\\n#22 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('ConfigService')\\n#23 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/gallery\\\/appinfo\\\/application.php(94): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('ConfigService')\\n#24 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OCA\\\\Gallery\\\\AppInfo\\\\Application->OCA\\\\Gallery\\\\AppInfo\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#25 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(115): Pimple\\\\Container->offsetGet('ConfigControlle...')\\n#26 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/DependencyInjection\\\/DIContainer.php(544): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('ConfigControlle...')\\n#27 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(91): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('ConfigControlle...')\\n#28 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ConfigControlle...', 'get', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#29 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#30 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#31 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/gallery\\\/c...')\\n#32 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#33 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php\",\"Line\":2068}","level":3,"time":"2017-01-26T16:41:32+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/gallery\/config?extramediatypes=1","user":"Test4","version":"11.0.1.2"}
{"reqId":"x","remoteAddr":"","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(136): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/lib\\\/Controller\\\/ViewController.php(199): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL, false)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/helper.php\",\"Line\":543}","level":3,"time":"2017-01-26T16:41:32+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","user":"Test4","version":"11.0.1.2"}
`

apache2/error.log

`[Thu Jan 26 16:06:00.912967 2017] [authz_core:error] [pid 17581] [client xx:56556] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Thu Jan 26 16:11:31.632874 2017] [authz_core:error] [pid 17579] [client xx:56583] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata
`

**Comment by xXSTrikeXx** [comment]
Can refere it to https://github.com/nextcloud/server/issues/2130

So i need to update the settings to an enabled group and not 'nothing'
