### ISSUE TITLE
Support SQLite

### ISSUE THREAD

**Issue by pellaeon** [pellaeon/registration#8]
Currently if using SQLite as database the following error will be thrown out on requesting verification link:

```
{"reqId":"Eaeke1KhaBnb9qWOh\/vW","remoteAddr":"x.x.x.x","app":"index","message":"Exception: {\"Exception\":                              \"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE \\\"oc_registration\\\" SET   \\\"registered\\\"=true WHERE \\\"token\\\" = ? ':\\n\\nSQLSTATE[HY000]: General error: 1 no such column: true\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116):                           Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...',                                                     Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/         Doctrine\\\/DBAL\\\/Connection.php(785): Doctrine\\\\DBAL\\\\DBALException::                                                                   driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException),      'UPDATE \\\"oc_regi...')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(108):                               Doctrine\\\\DBAL\\\\Connection->prepare('UPDATE \\\"oc_regi...')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/ db\\\/db.php(59): OC\\\\DB\\\\Connection->prepare('UPDATE `*PREFIX...', NULL, NULL)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/capps\\\/       registration\\\/db\\\/pendingregist.php(39): OC\\\\AppFramework\\\\Db\\\\Db->prepareQuery('UPDATE `*PREFIX...')\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/capps\\\/registration\\\/controller\\\/registercontroller.php(166): OCA\\\\Registration\\\\Db\\\\PendingRegist-                    >setRegistered('BIF0wU5sps7he8N...')\\n#6 [internal function]: OCA\\\\Registration\\\\Controller\\\\RegisterController-                        >createAccount('BIF0wU5sps7he8N...')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89):    OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Registration\\\\Controller\\\\RegisterController),
```

**Comment by cdamken** [comment]
Just to read it easier :
```
{"reqId":"Eaeke1KhaBnb9qWOh/vW","remoteAddr":"x.x.x.x","app":"index","message":"Exception: {"Exception":"Doctrine\DBAL\Exception\DriverException","Message":"An exception occurred while executing 'UPDATE "oc_registration" SET "registered"=true WHERE "token" = ? ':\n\nSQLSTATE[HY000]: General error: 1 no such column: true","Code":0,"Trace":"
n#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116):                           Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...',Object(Doctrine\DBAL\Driver\PDOException))
n#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(785): Doctrine\DBAL\DBALException::       driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException),UPDATE "oc_regi...')
n#2 /var/www/html/owncloud/lib/private/db/connection.php(108): Doctrine\DBAL\Connection->prepare('UPDATE "oc_regi...')
n#3 /var/www/html/owncloud/lib/private/appframework/ db/db.php(59): OC\DB\Connection->prepare('UPDATE `*PREFIX...', NULL, NULL)
n#4 /var/www/html/owncloud/capps/registration/db/pendingregist.php(39): OC\AppFramework\Db\Db->prepareQuery('UPDATE `*PREFIX...')
n#5 /var/www/html/owncloud/capps/registration/controller/registercontroller.php(166): OCA\Registration\Db\PendingRegist-setRegistered('BIF0wU5sps7he8N...')
n#6 [internal function]: OCA\Registration\Controller\RegisterController->createAccount('BIF0wU5sps7he8N...')
n#7 /var/www/html/owncloud/lib/private/appframework/http/dispatcher.php(159): call_user_func_array(Array, Array)
n#8 /var/www/html/owncloud/lib/private/appframework/http/dispatcher.php(89):    OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Registration\Controller\RegisterController),
```

**Comment by pellaeon** [comment]
SQLite is now supported.
